

package Jlableimg;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ajaykumar
 */
public class Jlableimg extends javax.swing.JFrame {

    /****************************************************************************************
     * Creates new form Jlableimg                                                           *
     ****************************************************************************************/
    static ServerSocket ss;
    static Socket s;
    static DataInputStream din;
    static DataOutputStream dout;
    String msgin =null;
    public File[] images;
     public File[] imagesrw;
    public File dir;
    public File dir1;
    
     public static int l = 0;
      private javax.swing.JProgressBar progressBar1;
      String counts="";

    Timer timer;

    public Jlableimg() {
        initComponents();
       
        dir = new File("/home/iiitbasar/Desktop/Prasna/");
       // dir1 = new File("/home/iiitbasar/Desktop/RW");
                 images = dir.listFiles();
                  //imagesrw = dir1.listFiles();
                 
                 
                 
                // {
                // images[l++] = f.getPath();
                //System.out.println(f.getName());
                //BufferedImage img = null;
                //try {
                  //  img = ImageIO.read(images[l]);

                   // jLabel1.setIcon(new ImageIcon(img));
                    //jLabel1.setIcon(new ImageIcon(img));
                //} catch (IOException ex) {
                  //  Logger.getLogger(Image.class.getName()).log(Level.SEVERE, null, ex);
                //}

           // }

           
            
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        iback = new javax.swing.JButton();
        Show = new javax.swing.JButton();
        mNext = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(132, 191, 254));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(126, 192, 232));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(149, 101, 233));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kkk.png"))); // NOI18N

        iback.setBackground(new java.awt.Color(254, 254, 254));
        iback.setFont(new java.awt.Font("URW Chancery L", 1, 18)); // NOI18N
        iback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Lock.png"))); // NOI18N
        iback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ibackActionPerformed(evt);
            }
        });

        Show.setBackground(new java.awt.Color(254, 254, 254));
        Show.setText("Show");
        Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowActionPerformed(evt);
            }
        });

        mNext.setBackground(new java.awt.Color(254, 254, 254));
        mNext.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        mNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nnext.png"))); // NOI18N
        mNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNextActionPerformed(evt);
            }
        });

        progressBar.setBackground(new java.awt.Color(153, 136, 204));
        progressBar.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        progressBar.setMaximum(45);
        progressBar.setFocusCycleRoot(true);
        progressBar.setString("45");
        progressBar.setStringPainted(true);
        progressBar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                progressBarAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel4.setFont(new java.awt.Font("URW Bookman L", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(8, 1, 1));

        jTable1.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"G1",  new Integer(0)},
                {"G2",  new Integer(0)},
                {"G3",  new Integer(0)},
                {"G4",  new Integer(0)},
                {"G5",  new Integer(0)},
                {"G6",  new Integer(0)},
                {"G7",  new Integer(0)},
                {"G8",  new Integer(0)},
                {"G9",  new Integer(0)},
                {"G10",  new Integer(0)}
            },
            new String [] {
                "Group", "Marks"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setAlignmentX(10.0F);
        jTable1.setAlignmentY(10.0F);
        jTable1.setEditingColumn(5);
        jTable1.setEditingRow(5);
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Group");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Marks");
        }

        jLabel5.setText("Designed and developed by 2k11");

        jLabel7.setFont(new java.awt.Font("Abyssinica SIL", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("          Prasna");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rlo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(iback, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(Show, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(mNext, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mNext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iback, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Show, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //int count = 0, pl = 0, mi = 0;
    //String[] imagenames = {"1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg",};
    int g1=0,g2=0,g3=0,g4=0,g5=0,g6=0,g7=0,g8=0,g9=0,g10=0;
             

    private void mNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNextActionPerformed
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nulll.png")));
                 jLabel4.setText("");
                  
                
                 
       
                 mNext.setEnabled(false);
                  Show.setEnabled(false);
                  iback.setEnabled(true);
                
                  
                  
                  
                  
                  
                  
                  
             BufferedImage img = null;
             BufferedImage img2 = null;
             BufferedImage img1 = null;
            try {
                
                img = ImageIO.read(images[l]);

                   // jLabel1.setIcon(new ImageIcon(img));
                jLabel1.setIcon(new ImageIcon(img));
                l++;
            } catch (IOException ex) {
                Logger.getLogger(Image.class.getName()).log(Level.SEVERE, null, ex);
            }
                  
                  
                 
        
       /* if (pl == 0) {
            pl++;
            count++;
        }
        mi = 0;
        ImageIcon[] imagelist = new ImageIcon[5];
        for (int i = 0; i < imagelist.length; i++) {

            imagelist[i] = new ImageIcon(getClass().getResource("/img/" + imagenames[i]));
        }
        if (count < 0) {
            
            count = 1;
        }
        if (count >= 0 && count < imagenames.length) {
            jLabel1.setIcon(imagelist[count]);
            count++;
        }*/

       //progressBar = new JProgressBar(JProgressBar.VERTICAL, 0, 59);
            
           
                  
            
            
            
            
            
        progressBar.setValue(45);
        ActionListener listener = new ActionListener() {
            int counter = 45;

            public void actionPerformed(ActionEvent ae) {
                counter--;
                counts=Integer.toString(counter);
                progressBar.setString(counts);
                progressBar.setValue(counter);
                if (counter < 1) {
                    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Time.png")));
                   // jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tu.png")));
                    //JOptionPane.showMessageDialog(null, "Kaboom!");
                    timer.stop();
                }
            }
        };
        timer = new Timer(1000, listener);

        timer.start();
        //JOptionPane.showMessageDialog(null, progressBar);

// TODO add your handling code here:
    }//GEN-LAST:event_mNextActionPerformed

    private void ibackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ibackActionPerformed
         mNext.setEnabled(false);
          iback.setEnabled(false);
           Show.setEnabled(true);
        timer.stop();
        msgin =null;
        System.out.println(msgin);
       // jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Lock.png")));
        
        /* String[] imagenames1 = {"r.png","w.jpg"};
         ImageIcon[] imagelist1=new ImageIcon[2];
       
         for(int j=0;j<imagelist1.length;j++)
         {
            
         imagelist1[j]=new ImageIcon(getClass().getResource("/img/"+imagenames1[j]));
         }*/
      
        try {
               
            
             
            System.out.println("1");
           
            dout = new DataOutputStream(s.getOutputStream());
            while (msgin==null) {
                System.out.println("1");
                din = new DataInputStream(s.getInputStream());
                msgin = din.readUTF();
                System.out.println(msgin);

           // if(cc==1)
                //{
                //  cc++;
            }
            
           // s.close();
//           ss.close();
            
            

        } //}
        catch (IOException e) {

        }

        System.out.println("close");
        
// TODO add your handling code here:
    }//GEN-LAST:event_ibackActionPerformed

    private void progressBarAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_progressBarAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_progressBarAncestorAdded

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged

    private void ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowActionPerformed
        
        mNext.setEnabled(true);
        Show.setEnabled(false);
        iback.setEnabled(true);
       
        
        
        
        
        
        if (l > images.length - 1) {
            mNext.setEnabled(false);
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tt.png")));
        }
        
         DefaultTableModel model1=(DefaultTableModel) jTable1.getModel();
                  g1=(int)model1.getValueAt(0, 1);
                  g2=(int)model1.getValueAt(1, 1);
                  g3=(int)model1.getValueAt(2, 1);
                  g4=(int)model1.getValueAt(3, 1);
                  g5=(int)model1.getValueAt(4, 1);
                  g6=(int)model1.getValueAt(5, 1);
                  g7=(int)model1.getValueAt(6, 1);
                  g8=(int)model1.getValueAt(7, 1);
                  g9=(int)model1.getValueAt(8, 1);
                  g10=(int)model1.getValueAt(9, 1);
        
        
        
        
        
        
        
        
        
        
        
        String temp="";
        for(int kk=4;kk<msgin.length();kk++)
        {
            temp=temp+(msgin.charAt(kk));
        }
        if (msgin.charAt(0) == '0') {
                // jLabel3.setIcon(imagelist1[1]);
            int nn=3;
                System.out.println("w");
                
               // try {
                //BufferedImage img2 = ImageIO.read(imagesrw[1]);
                //jLabel1.setIcon(new ImageIcon(img2));
            //} catch (IOException ex) {
              //  Logger.getLogger(Jlableimg.class.getName()).log(Level.SEVERE, null, ex);
            //}
                
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/W.png")));
                jLabel4.setText("");
            } 
        else if (msgin.charAt(0)=='1'||msgin.charAt(0)=='3'){
                System.out.println("R");
                //jLabel3.setIcon(imagelist1[0]);
                int mm=3;
                BufferedImage img1 = null;
                
           // try {
             //   img1 = ImageIO.read(imagesrw[0]);
               // jLabel1.setIcon(new ImageIcon(img1));
            //} catch (IOException ex) {
              //  Logger.getLogger(Jlableimg.class.getName()).log(Level.SEVERE, null, ex);
            //}

                   // jLabel1.setIcon(new ImageIcon(img));
                
                   // jLabel1.setIcon(new ImageIcon(img));
               // jLabel1.setIcon(new ImageIcon(img1));
               jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/R.png")));
                 jLabel4.setText("Ans::"+temp);
                 String sss="";
                 
                 DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
                 sss=sss+'G'+msgin.charAt(2);
                 System.out.println(msgin.charAt(2));
                 System.out.println(sss);
                  //System.out.println(jTable1.getSelectedRow());
                 if(msgin.charAt(2)=='1')
                 {
                     
                     g1++;
                     g1++;
                     if(msgin.charAt(0)=='3')
                         g1--;
                    model.setValueAt(g1,0, 1);
                 }
                 
                 if(msgin.charAt(2)=='2')
                 {
                     g2++;
                     g2++;
                     if(msgin.charAt(0)=='3')
                         g2--;
                    model.setValueAt(g2,1, 1);
                    
                    
                 }
                 if(msgin.charAt(2)=='3')
                 {
                     g3++;
                     g3++;
                     if(msgin.charAt(0)=='3')
                         g3--;
                    model.setValueAt(g3,2, 1);
                 }
                 if(msgin.charAt(2)=='4')
                 {
                     g4++;
                     g4++;
                     if(msgin.charAt(0)=='3')
                         g4--;
                    model.setValueAt(g4,3, 1);
                 }
                 if(msgin.charAt(2)=='5')
                 {
                     g5++;
                     g5++;
                     if(msgin.charAt(0)=='3')
                         g5--;
                    model.setValueAt(g5,4, 1);
                 }
                 
                 if(msgin.charAt(2)=='6')
                 {
                     g6++;
                     g6++;
                     if(msgin.charAt(0)=='3')
                         g6--;
                    model.setValueAt(g6,5, 1);
                 }
                 if(msgin.charAt(2)=='7')
                 {
                     g7++;
                     g7++;
                     if(msgin.charAt(0)=='3')
                         g7--;
                    model.setValueAt(g7,6, 1);
                 }
                 if(msgin.charAt(2)=='8')
                 {
                     g8++;
                     g8++;
                     if(msgin.charAt(0)=='3')
                         g8--;
                    model.setValueAt(g8,7, 1);
                 }
                
                 if(msgin.charAt(2)=='9')
                 {
                     g9++;
                     g9++;
                     if(msgin.charAt(0)=='3')
                         g9--;
                    model.setValueAt(g9,8, 1);
                    
                    
                 }
                 if(msgin.charAt(2)=='0')
                 {
                     g10++;
                     g10++;
                     if(msgin.charAt(0)=='3')
                         g10--;
                    model.setValueAt(g10,9, 1);
                 }
                 
                 
                 
                 
                 
                 
               //  model.setValueAt(mm,jTable1.getSelectedRow(), 1);
                 
                // jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/r.png")));
            }
        else
        {
            // jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Time.png")));
            jLabel4.setText("Ans::"+temp);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_ShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
           try{
               ss = new ServerSocket(1221);
           
            s = ss.accept();
               
           }
           catch(Exception e)
           {
               
           }
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jlableimg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jlableimg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jlableimg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jlableimg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jlableimg().setVisible(true);
                //new CountDownProgressBar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Show;
    private javax.swing.JButton iback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton mNext;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
    

}